// <auto-generated />
using System;
using BT_CodeFirst3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT_CodeFirst3.Migrations
{
    [DbContext(typeof(ClassDbContext))]
    [Migration("20240411040814_ver1")]
    partial class ver1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BT_CodeFirst3.Models.KetQua", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MASV");

                    b.Property<string>("MaMH")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MAMH");

                    b.Property<byte>("LanThi")
                        .HasColumnType("tinyint")
                        .HasColumnName("LANTHI");

                    b.Property<decimal>("Diem")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("DIEM");

                    b.Property<string>("KQ")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("KQ");

                    b.HasKey("MaSV", "MaMH", "LanThi");

                    b.HasIndex("MaMH");

                    b.ToTable("KetQuas");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MAKH");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("SLSV");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TENKH");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MAMH");

                    b.Property<byte>("SoTiet")
                        .HasColumnType("tinyint")
                        .HasColumnName("SOTIET");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)")
                        .HasColumnName("TENMH");

                    b.HasKey("MaMH");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MASV");

                    b.Property<decimal>("DiemTB")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("DIEMTB");

                    b.Property<string>("HoSV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HOSV");

                    b.Property<decimal>("HocBong")
                        .HasColumnType("money")
                        .HasColumnName("HOCBONG");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("MAKH");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGSINH");

                    b.Property<string>("NoiSinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NOISINH");

                    b.Property<string>("Phai")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("PHAI");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TENSV");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.KetQua", b =>
                {
                    b.HasOne("BT_CodeFirst3.Models.MonHoc", "MonHoc")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_MonHoc");

                    b.HasOne("BT_CodeFirst3.Models.SinhVien", "SinhVien")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_SinhVien");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.HasOne("BT_CodeFirst3.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SinhVien_Khoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.Khoa", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.MonHoc", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
