// <auto-generated />
using System;
using BT_CodeFirst3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT_CodeFirst3.Migrations
{
    [DbContext(typeof(ClassDbContext))]
    partial class ClassDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BT_CodeFirst3.Models.KetQua", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("MaMH")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<byte>("LanThi")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Diem")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("KQ")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("MaSV", "MaMH", "LanThi");

                    b.HasIndex("MaMH");

                    b.ToTable("KetQuas");

                    b.HasData(
                        new
                        {
                            MaSV = "SV01",
                            MaMH = "CSDL",
                            LanThi = (byte)1,
                            Diem = 3m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV01",
                            MaMH = "CSDL",
                            LanThi = (byte)2,
                            Diem = 6m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV01",
                            MaMH = "TTNT",
                            LanThi = (byte)1,
                            Diem = 5m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV01",
                            MaMH = "TTNT",
                            LanThi = (byte)2,
                            Diem = 6m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV01",
                            MaMH = "MMT",
                            LanThi = (byte)1,
                            Diem = 5m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV02",
                            MaMH = "CSDL",
                            LanThi = (byte)1,
                            Diem = 4m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV02",
                            MaMH = "CSDL",
                            LanThi = (byte)2,
                            Diem = 7m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV02",
                            MaMH = "MMT",
                            LanThi = (byte)1,
                            Diem = 10m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV02",
                            MaMH = "CTDL",
                            LanThi = (byte)1,
                            Diem = 9m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV03",
                            MaMH = "CSDL",
                            LanThi = (byte)1,
                            Diem = 2m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV03",
                            MaMH = "CSDL",
                            LanThi = (byte)2,
                            Diem = 5m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV03",
                            MaMH = "MMT",
                            LanThi = (byte)1,
                            Diem = 2m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV03",
                            MaMH = "MMT",
                            LanThi = (byte)2,
                            Diem = 4m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV04",
                            MaMH = "CSDL",
                            LanThi = (byte)1,
                            Diem = 4m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV04",
                            MaMH = "CTDL",
                            LanThi = (byte)1,
                            Diem = 10m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV05",
                            MaMH = "CSDL",
                            LanThi = (byte)1,
                            Diem = 7m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV05",
                            MaMH = "MMT",
                            LanThi = (byte)1,
                            Diem = 2m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV05",
                            MaMH = "MMT",
                            LanThi = (byte)2,
                            Diem = 5m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV06",
                            MaMH = "TTNT",
                            LanThi = (byte)1,
                            Diem = 6m,
                            KQ = ""
                        },
                        new
                        {
                            MaSV = "SV06",
                            MaMH = "DHMT",
                            LanThi = (byte)1,
                            Diem = 10m,
                            KQ = ""
                        });
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.Khoa", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("SLSV")
                        .HasColumnType("int");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            MaKH = "HTTT",
                            SLSV = 0,
                            TenKH = "Hệ thống thông tin"
                        },
                        new
                        {
                            MaKH = "MANG",
                            SLSV = 0,
                            TenKH = "Mạng và truyền thông"
                        },
                        new
                        {
                            MaKH = "CNPM",
                            SLSV = 0,
                            TenKH = "Công nghệ phần mềm"
                        },
                        new
                        {
                            MaKH = "KTMT",
                            SLSV = 0,
                            TenKH = "Kỹ thuật máy tính"
                        },
                        new
                        {
                            MaKH = "KHMT",
                            SLSV = 0,
                            TenKH = "Khoa học máy tính"
                        });
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<byte>("SoTiet")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHocs");

                    b.HasData(
                        new
                        {
                            MaMH = "CSDL",
                            SoTiet = (byte)45,
                            TenMH = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            MaMH = "TTNT",
                            SoTiet = (byte)45,
                            TenMH = "Trí tuệ nhân tạo"
                        },
                        new
                        {
                            MaMH = "MMT",
                            SoTiet = (byte)45,
                            TenMH = "Mạng máy tính"
                        },
                        new
                        {
                            MaMH = "DHMT",
                            SoTiet = (byte)60,
                            TenMH = "Đồ họa máy tính"
                        },
                        new
                        {
                            MaMH = "CTDL",
                            SoTiet = (byte)60,
                            TenMH = "Cấu trúc dữ liệu"
                        });
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("DiemTB")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("HoSV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("HocBong")
                        .HasColumnType("money");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("NGSinh")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiSinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Phai")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKH");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSV = "SV01",
                            DiemTB = 0m,
                            HoSV = "Lê Kim",
                            HocBong = 130000m,
                            MaKH = "HTTT",
                            NGSinh = new DateTime(1990, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "Hà Nội",
                            Phai = "Nữ",
                            TenSV = "Lan"
                        },
                        new
                        {
                            MaSV = "SV02",
                            DiemTB = 0m,
                            HoSV = "Trần Minh",
                            HocBong = 150000m,
                            MaKH = "MANG",
                            NGSinh = new DateTime(1992, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "Bình Định",
                            Phai = "Nam",
                            TenSV = "Chánh"
                        },
                        new
                        {
                            MaSV = "SV03",
                            DiemTB = 0m,
                            HoSV = "Lê An",
                            HocBong = 170000m,
                            MaKH = "HTTT",
                            NGSinh = new DateTime(1991, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "Hải Phòng",
                            Phai = "Nữ",
                            TenSV = "Tuyết"
                        },
                        new
                        {
                            MaSV = "SV04",
                            DiemTB = 0m,
                            HoSV = "Trần Anh",
                            HocBong = 80000m,
                            MaKH = "MANG",
                            NGSinh = new DateTime(1993, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "TpHCM",
                            Phai = "Nam",
                            TenSV = "Tuấn"
                        },
                        new
                        {
                            MaSV = "SV05",
                            DiemTB = 0m,
                            HoSV = "Trần Thị",
                            HocBong = 0m,
                            MaKH = "CNPM",
                            NGSinh = new DateTime(1991, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "TpHCM",
                            Phai = "Nữ",
                            TenSV = "Mai"
                        },
                        new
                        {
                            MaSV = "SV06",
                            DiemTB = 0m,
                            HoSV = "Lê Thị Thu",
                            HocBong = 0m,
                            MaKH = "HTTT",
                            NGSinh = new DateTime(1991, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "An Giang",
                            Phai = "Nữ",
                            TenSV = "Thủy"
                        },
                        new
                        {
                            MaSV = "SV07",
                            DiemTB = 0m,
                            HoSV = "Nguyễn Kim",
                            HocBong = 180000m,
                            MaKH = "CNPM",
                            NGSinh = new DateTime(1990, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "Hà Nội",
                            Phai = "Nữ",
                            TenSV = "Thư"
                        },
                        new
                        {
                            MaSV = "SV08",
                            DiemTB = 0m,
                            HoSV = "Lê Văn",
                            HocBong = 190000m,
                            MaKH = "HTTT",
                            NGSinh = new DateTime(1992, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiSinh = "TpHCM",
                            Phai = "Nam",
                            TenSV = "Long"
                        });
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.KetQua", b =>
                {
                    b.HasOne("BT_CodeFirst3.Models.MonHoc", "MonHoc")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_MonHoc");

                    b.HasOne("BT_CodeFirst3.Models.SinhVien", "SinhVien")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_SinhVien");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.HasOne("BT_CodeFirst3.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SinhVien_Khoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.Khoa", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.MonHoc", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("BT_CodeFirst3.Models.SinhVien", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
